version: "3.8"

services:
    prometheus:
        image: prom/prometheus:latest
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
        ports:
            - 9090:9090
    node-exporter:
        image: prom/node-exporter:latest
        volumes:
            - ./node_exporter.flags:/node-exporter/flags
        ports:
            - 9100:9100

volumes:
    prometheus-data:
